app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired


class CentreForm(FlaskForm):
    """
    Form for admin to add or edit a centre
    """

    serviceApprovalNumber = StringField('Service Approval Number', validators = [DataRequired()])
    providerApprovalNumber = StringField('Provider Approval Number', validators = [DataRequired()])
    serviceName = StringField('Service Name', validators = [DataRequired()])
    providerLegalName = StringField('Provider Legal Name', validators = [DataRequired()])
    serviceAddress = StringField('Service Address', validators = [DataRequired()])
    suburb = StringField('Suburb', validators = [DataRequired()])
    state = StringField('State', validators = [DataRequired()])
    postcode = IntegerField('Postcode', validators = [DataRequired()])
    phone = StringField('Phone', validators = [DataRequired()])
    fax = StringField('Fax', validators = [DataRequired()])
    emailAddress = StringField('Email', validators = [DataRequired()])
    conditionsOnApproval = StringField('Conditions on Approval', validators = [DataRequired()])
    numberOfApprovedPlaces = IntegerField('Number of Approved Places', validators = [DataRequired()])
    overallRating = StringField('Overall Rating', validators = [DataRequired()])
    type = StringField('Type', validators = [DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

# local imports
from config import app_config

login_manager = LoginManager()

def create_app(config_name):
	app = Flask(__name__, instance_relative_config = True)
	app.config.from_object(app_config[config_name])
	app.config.from_pyfile('config.py')

	Bootstrap(app)

	# login_manager.init_app(app)
	# login_manager.login_message = "You must be logged in to access this page."
	# login_manager.login_view = "auth.login"

	from .admin import admin as admin_blueprint
	app.register_blueprint(admin_blueprint, url_prefix = '/admin')

	# from .auth import auth as auth_blueprint
	# app.register_blueprint(auth_blueprint)

	from .home import home as home_blueprint
	app.register_blueprint(home_blueprint)

	return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

app/admin/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import admin
from .forms import CentreForm

import requests

base_url = 'http://localhost:8080'


@admin.route('/dashboard', methods = ['GET', 'POST'])
# @login_required
def dashboard():
	"""
	Dashboard view
	"""
	url = base_url+'/centres'
	centres = requests.get(url).json()

	weather_url = base_url+'/weather'
	weather = requests.get(weather_url).json()

	return render_template('admin/dashboard.html', centres = centres, weather=weather, title="Dashboard")

@admin.route('/dashboard/add', methods = ['GET', 'POST'])
#@login_required
def add_centre():
	"""
	Add Centre
	"""

	add_centre = True

	url = base_url+'/centres'

	form = CentreForm()
	if form.validate_on_submit():
		service_approval_number = form.serviceApprovalNumber.data
		provider_approval_number = form.providerApprovalNumber.data
		service_name = form.serviceName.data
		provider_legal_name = form.providerLegalName.data
		service_address = form.serviceAddress.data
		suburb = form.suburb.data
		state = form.state.data
		postcode = form.postcode.data
		phone = form.phone.data
		fax = form.fax.data
		email_address = form.emailAddress.data
		conditions_on_approval = form.conditionsOnApproval.data
		number_of_approved_places = form.numberOfApprovedPlaces.data
		overall_rating = form.overallRating.data
		type = form.type.data

		try:
			requests.post(url, data = {'centres':centres})
		except:
			flash('Service name already exists')
		return redirect(url_for('admin.dashboard'))

	return render_template('admin/centre.html', action = 'Add', add_centre = add_centre, form = form, title="Add Centre")



@admin.route('/dashboard/edit/<int:id>', methods = ['GET', 'POST'])
#@login_required
def edit_centre(id):
	"""
	Edit Centre
	"""

	add_centre=False

	url = base_url+'/centres/{id}'
	url = url.format(id = id)

	centre = requests.get(url).json()
	print(centre)
	print(centre['service_approval_number'])

	form = CentreForm(obj=centre)

	if form.validate_on_submit():
		centre['service_approval_number'] = form.serviceApprovalNumber.data
		centre['provider_approval_number'] = form.providerApprovalNumber.data
		centre['service_name'] = form.serviceName.data
		centre['provider_legal_name'] = form.providerLegalName.data
		centre['service_address'] = form.serviceAddress.data
		centre['suburb'] = form.suburb.data
		centre['state'] = form.state.data
		centre['postcode'] = form.postcode.data
		centre['phone'] = form.phone.data
		centre['fax'] = form.fax.data
		centre['email_address'] = form.emailAddress.data
		centre['conditions_on_approval'] = form.conditionsOnApproval.data
		centre['number_of_approved_places'] = form.numberOfApprovedPlaces.data
		centre['overall_rating'] = form.overallRating.data
		centre['type'] = form.type.data
		requests.put(url, data = {'centre': centre})
		flash('You have successfully edited the centre')

		return redirect(url_for('admin.dashboard'))

	form.serviceApprovalNumber.data = centre['service_approval_number']
	form.providerApprovalNumber = centre['provider_approval_number']
	form.serviceName = centre['service_name']
	form.providerLegalName = centre['provider_legal_name']
	form.serviceAddress = centre['service_address']
	form.suburb = centre['suburb']
	form.state = centre['state']
	form.postcode = centre['postcode']
	form.phone = centre['phone']
	form.fax = centre['fax']
	form.emailAddress = centre['email_address']
	form.conditionsOnApproval = centre['conditions_on_approval']
	form.numberOfApprovedPlaces = centre['number_of_approved_places']
	form.overallRating = centre['overall_rating']
	form.type = centre['type']

	return render_template('admin/centre.html', action='Edit', add_centre=add_centre, form = form, centre = centre, title='Edit Centre')

@admin.route('/dashboard/delete/<int:id>', methods=['GET', 'POST'])
#@login_required
def delete_centre(id):
	"""
	Delete Centre
	"""

	url = base_url+'/centres/{id}'
	url = url.format(id = id)

	centre = requests.delete(url).json()

	flash('You have successfully deleted the centre')

	return redirect(url_for('admin.dashboard'))

@admin.route('/dashboard/save/<int:id>', methods=['GET', 'POST'])
def save_centre(id):
	url = base_url+'/save/{id}'
	url = url.format(id = id)
	requests.get(url)

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template, redirect, url_for, request
from flask_login import login_required

from . import home

import requests

base_url = 'http://localhost:8080'

@home.route('/')
def homepage():
	return render_template('home/index.html', title = 'Welcome')

@home.route('/search')
def search():
	"""
	Search a Childcare Centre
	"""
	url = base_url+'/centres'
	centres = requests.get(url).json()

	return render_template('home/search.html', centres = centres, title="Search")

app/templates/base.html
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{ title }} | Enroll My Kid</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <!-- In the head tag, include link to Font Awesome CSS so we can use icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}"> Enrollmykid</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                
                  <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                  <li><a href="{{ url_for('admin.dashboard') }}">Centres</a></li>
                
              </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        <li><a href="{{ url_for('admin.dashboard') }}">Centres</a></li>
                    </ul>
                    <p class="copyright text-muted small">Copyright © 2019. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Enroll My Kid</h1>
                    <h3>The simplest way to find Childcare</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}